# Friendly name -> JSON key in app_shortcuts.json (used for shortcut lookup AND routing)
APP_SHORTCUT_ALIASES = {
    "text editor": "text-editor",
    "gnome text editor": "text-editor",
    "gnome-text-editor": "text-editor",
    "files": "nautilus",
    "file manager": "nautilus",
    "image viewer": "loupe",
    "document viewer": "papers",
    "pdf viewer": "papers",
    "terminal": "ptyxis",
    "videos": "showtime",
    "video player": "showtime",
    "gnome videos": "showtime",
    "system monitor": "system-monitor",
    "gnome system monitor": "system-monitor",
    "chrome": "google-chrome",
    "google chrome": "google-chrome",
    "audio player": "decibels",
    "music player": "decibels",
    "disk usage": "baobab",
    "disk usage analyzer": "baobab",
    "disk analyzer": "baobab",
    "scanner": "simple-scan",
    "document scanner": "simple-scan",
    "virtual machines": "boxes",
}
